[package]
name = "template_searcher"
version = "0.1.1"
authors = ["Nigecat"]
edition = "2018"

[dependencies]
confy = "0.4.0"
hotkey = "0.3.1"
web-view = "0.6.3"
snailquote = "0.3.0"
serde = { version = "1.0.115", features = ["derive"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "Template Searcher.exe"
ProductName = "Template Searcher"
FileDescription = "Discord Template Searcher"