[package]
name = "template-searcher-scraper"
version = "0.1.0"
authors = ["Nigecat"]
edition = "2018"

[dependencies]
console = "0.12.0"
indicatif = "0.15.0"
serde_json = "1.0.57"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }