[package]
name = "template_searcher"
version = "0.1.0"
authors = ["Nigecat"]
edition = "2018"

[dependencies]
confy = "0.4.0"
hotkey = "0.3.1"
web-view = "0.6.3"
serde = { version = "1.0.115", features = ["derive"] }